# En /var/www/ln-chat-poetry/docker-compose.yml

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: vanna-backend-test # <-- CAMBIO: Nombre único
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - VANNA_VECTOR_DB_PATH=${VANNA_VECTOR_DB_PATH}
    env_file: .env
    ports:
      - "8001:8000" # <-- CAMBIO: Puerto único
    volumes:
      - ./chroma_data_vps:/data/chroma
      - ./vps_backups:/app/backend/backups
    networks:
      - vanna_net_test # <-- CAMBIO: Red única
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: vanna-frontend-test # <-- CAMBIO
    env_file: .env
    environment:
      STREAMLIT_API_BASE_URL: ${STREAMLIT_API_BASE_URL:-http://backend:8000}
    ports:
      - "8502:8501" # <-- CAMBIO
    depends_on: [backend]
    networks:
      - vanna_net_test # <-- CAMBIO
    restart: unless-stopped

# Definir los nuevos nombres de volumen y red

networks:
  vanna_net_test: {} # <-- CAMBIO